[build]
  base    = "frontend"
  command = "npm run build"
  publish = "frontend/build"

[build.environment]
  REACT_APP_API_URL = "https://carto-facilesn.onrender.com"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
